name: Docrot Detector
on:
  push:

jobs:
  docrot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: SuchiiJain/CS4485_Capstone@github-integration
        with:
          repo_path: .
          create_issue: "true"
          database_url: ${{ secrets.DATABASE_URL }}
          fail_on_db_error: "true"