# .github/workflows/docrot.yml
name: Docrot Detector
on: [push]
jobs:
  docrot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SuchiiJain/CS4485_Capstone@portias-supabase-integration